<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="piston">
	<link name="riser">
            <pose>-0.12 0.0 0.5 0 0 0</pose>
            <inertial>
                <pose>0 0 -0.5 0 0 0</pose>
                <inertia>
                    <ixx>0.01</ixx>
                    <ixy>0</ixy>
                    <ixz>0</ixz>
                    <iyy>0.01</iyy>
                    <iyz>0</iyz>
                    <izz>0.01</izz>
                </inertia>
                <mass>.4</mass>
            </inertial>
            <collision name="collision">
                <geometry>
                    <cylinder>
                        <radius>0.05</radius>
                        <length>0.2</length>
                    </cylinder>
                </geometry>
            </collision>
            <visual name="visual">
                <geometry>
                    <cylinder>
                        <radius>0.05</radius>
                        <length>0.2</length>
                    </cylinder>
                </geometry>
                <material>
                    <script>Gazebo/Purple</script>
                </material>
            </visual>
        </link>

        <link name="palm">
            <pose>0.0 0.0 0.05 0 0 0</pose>
            <inertial>
                <inertia>
                    <ixx>0.01</ixx>
                    <ixy>0</ixy>
                    <ixz>0</ixz>
                    <iyy>0.01</iyy>
                    <iyz>0</iyz>
                    <izz>0.01</izz>
                </inertia>
                <mass>0.4</mass>
            </inertial>
            <collision name="collision">
                <geometry>
                    <cylinder>
                        <radius>0.07</radius>
                        <length>0.3</length>
                    </cylinder>
                </geometry>
            </collision>
            <visual name="visual">
                <geometry>
                    <cylinder>
                        <radius>0.07</radius>
                        <length>0.3</length>
                    </cylinder>
                </geometry>
                <material>
                    <script>Gazebo/Red</script>
                </material>
            </visual>
        </link>

        <static>false</static>

        <joint name="palm_riser" type="prismatic">
            <child>palm</child>
            <parent>riser</parent>
            <limit>
            	<effort>10.0</effort>
                <lower>0</lower>
                <upper>0.9</upper>
                <velocity>0.5</velocity>
            </limit>
            <origin xyz="0 0 1" />
        </joint>
</robot>
<!-- 

<origin xyz="${chassis_length/2} ${chassis_length/2} ${joint_height}"/>
    <child link="${namespace}/piston"/>
    <limit effort="10.0" lower="0" upper="1.0" velocity="0.5"/> -->