  type: "diff_drive_controller/DiffDriveController"
  publish_rate: 50

  left_wheel:  'blw_1'
  right_wheel: 'brw_1'

  wheel_separation: 0.24

  wheel_radius : 0.035

  # Odometry covariances for the encoder output of the robot. These values should
  # be tuned to your robot's sample odometry data, but these values are a good place
  # to start
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]

  # Top level frame (link) of the robot description
  # base_frame_id: base_link
  # odom_frame_id: odom

  # Velocity and acceleration limits for the robot
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.3   # m/s
      has_acceleration_limits: true
      max_acceleration       : 0.3  # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 1.4   # rad/s 80 degrees
      has_acceleration_limits: true
      max_acceleration       : 1.4   # rad/s^2
